### ISSUE TITLE
Update to 3.6.1

### ISSUE THREAD

**Issue by ostrosablin** [fancypantalons/nethackds#17]
NetHack 3.6.1 was released on 27 Apr.

It also incorporates a lot of changes, which could be used on UI side, e.g. this option

> herecmd_menu
> 
> When using a windowport that supports mouse and clicking on yourself or next to you, show a menu of possible actions for the location. Same as herecmdmenu and therecmdmenu commands.

**Comment by fancypantalons** [comment]
Yup, this is definitely on my radar.

More immediately, I'm also looking at supporting the STATUS_VIA_WINDOWPORT and STATUS_HILITES  features, which should allow me to 1) eliminate another custom patchset, getting this port even closer to vanilla (ultimately, I'd love to move this to being a straight overlay atop the 3.6 codebase with no changes to the core), and 2) flip to the now-standardizing mechanism for highlights.

**Comment by fancypantalons** [comment]
So I've taken a new approach to this.  If you look at my profile, you'll see I've directly forked the NetHack git tree, and then dropped in my NDS porting layer.  The latest commit in the NetHackDS branch of that tree merges in the 3.6.1 changes.  I still have some work to do before I cut a 3.6.1 build (in particular, I want to add STATUS_HILITES support now that it appears its stabilized), but that's where the work will get done, as it'll make it a *lot* easier to track vanilla if I just build off their tree directly.
